version: '3.8'

services:
  server:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
