name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Start and check server
      run: |
        cd server
        timeout 60s npm run dev &
        SERVER_PID=$!
        sleep 30
        if curl -f http://localhost:3000/api/v1/health; then
          echo "Server is running"
        else
          echo "Server health check failed"
          exit 1
        fi
        kill $SERVER_PID || true

    - name: Install client dependencies
      run: |
        cd client
        npm install

    - name: Build client
      run: |
        cd client
        npm run build

    - name: Start and check client
      run: |
        cd client
        timeout 60s npm run dev &
        CLIENT_PID=$!
        sleep 30
        if curl -f http://localhost:5173; then
          echo "Client is running"
        else
          echo "Client health check failed"
          exit 1
        fi
        kill $CLIENT_PID || true
